INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16163', 'Active: Temporarily increases the size of your head.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16164', 'Active: Temporarily increases your lung capacity.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16165', 'Active: Temporarily increases the distance you can fall without sustaining damage.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16166', 'Active: Temporarily increases resistance to damage from falling.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16167', 'Active: Ignites a firecracker.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16168', 'Active: Play music for a short duration.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16169', 'Active: Ignites a large firecracker.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16170', 'Chance: Temporarily decreases your target\'s will to attack during a physical attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16171', 'Chance: Temporarily increases your target\'s will to attack during a physical attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16172', 'Chance: Momentarily decreases your target\'s speed during a physical attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16173', 'Chance: Temporarily decreases your target\'s will to attack during a critical attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16174', 'Chance: Temporarily increases your target\'s will to attack during a critical attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16175', 'Chance: Momentarily decreases your target\'s speed during a critical attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16176', 'Chance: Momentarily decreases your target\'s speed during a magic attack. Effect 3.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16177', 'Passive: Increases lung capacity.', '3');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16178', 'Passive: Increases the height from which you can fall without sustaining damage.', '3');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16179', 'Passive: Raises resistance to damage from falling.', '3');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16180', 'Active: Temporarily decreases your target\'s Atk. Spd.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16181', 'Active: Temporarily increases Dodge.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16182', 'Active: Temporarily causes a target to bleed heavily.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16183', 'Active: Restores your CP.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16184', 'Active: Inflicts damage by throwing a boulder.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16185', 'Active: Momentarily frightens away your target.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16186', 'Active: Detonates a fireball by compressing the air around the caster.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16187', 'Active: Decreases your target\'s will to attack.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16188', 'Active: Decreases your target\'s will to attack.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16189', 'Active: Increases your target\'s will to attack.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16190', 'Active: Temporarily increases your Accuracy.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16191', 'Active: Temporarily holds your target. Your target cannot be affected by any additional hold attacks while the effect lasts.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16192', 'Active: Launches a sacred magic attack.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16193', 'Active: Temporarily increases the power of HP recovery magic.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16194', 'Active: Temporarily increases the effectiveness of HP recovery magic.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16195', 'Active: Instantly restores your HP.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16196', 'Active: Temporarily increases your M. Atk.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16197', 'Active: Temporarily increases your maximum CP.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16198', 'Active: Increases your maximum HP temporarily and restores HP by the increased amount.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16199', 'Active: Temporarily increases your maximum HP.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16200', 'Active: Temporarily increases your maximum MP.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16201', 'Active: Temporarily increases your M. Def.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16202', 'Active: Burns up your enemy\'s MP.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16203', 'Active: Increases your MP recharge recovery rate.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16204', 'Active: Regenerates MP.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16205', 'Active: Unleashes a general attack and temporarily decreases your magic attack power during PvP.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16206', 'Active: Temporarily increases your P. Atk.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16207', 'Active: Temporarily paralyzes a target.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16208', 'Active: Temporarily increases your P. Def.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16209', 'Active: Temporarily poisons your target.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16210', 'Active: Temporarily decreases your target\'s P.Atk. during PvP.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16211', 'Active: Temporarily increases your P.Atk. during PvP.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16212', 'Active: Teleports the caster to a village. Cannot be used in a specially designated place such as the GM Consultation Service.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16213', 'Active: Resurrects a corpse.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16214', 'Active: Emits an area of effect earth attack.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16215', 'Active: Emits an area of effect fire attack.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16216', 'Active: Emits an area of effect sacred magic attack.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16217', 'Active: Emits elemental damage over an area.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16218', 'Active: Emits an area of effect dark attack.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16219', 'Active: Emits an area of effect water attack.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16220', 'Active: Emits an area of effect wind attack.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16221', 'Active: Temporarily puts your target to sleep. Your target cannot be affected by any additional sleep attacks while the effect lasts.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16222', 'Active: Temporarily decreases your target\'s speed.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16223', 'Active: Temporarily stuns your target.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16224', 'Active: Inflicts an earth attack.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16225', 'Active: Inflicts a fire attack.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16226', 'Active: Inflicts a sacred magic attack.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16227', 'Active: Inflicts elemental damage.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16228', 'Active: Inflicts a dark attack.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16229', 'Active: Inflicts a water attack.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16230', 'Active: Inflicts a wind attack.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16231', 'Active: Cancels your enemy\'s target.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16232', 'Active: Temporarily petrifies your target.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16233', 'Active: Launches a dark attack.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16234', 'Active: Has a chance to open doors and treasure chests. Requires Keys of a Thief.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16235', 'Active: Absorbs HP from your target.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16236', 'Active: Inflicts a water attack.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16237', 'Active: Inflicts a fire attack.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16238', 'Chance: Momentarily decreases your target\'s Atk. Spd. during a physical attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16239', 'Chance: Momentarily causes your target to bleed during a physical attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16240', 'Chance: Momentarily frightens away your target during a physical attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16241', 'Chance: Momentarily holds your target during a physical attack. Your target cannot be affected by any additional hold attacks while the effect lasts.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16242', 'Chance: Momentarily poisons your target during a physical attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16243', 'Chance: Momentarily petrifies your target during a physical attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16244', 'Chance: Momentarily decreases your target\'s Atk. Spd. during a critical attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16245', 'Chance: Momentarily causes your target to bleed during a critical attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16246', 'Chance: Momentarily frightens your target during a critical attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16247', 'Chance: Momentarily holds your target during a critical attack. Your target cannot be affected by any additional hold attacks while the effect lasts.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16248', 'Chance: Momentarily poisons your target during a critical attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16249', 'Chance: Momentarily petrifies your target during a critical attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16250', 'Chance: Has a chance to decrease the Atk. Spd. of a target that damages you..', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16251', 'Chance: Has a chance to increase your Evasion when you take damage.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16252', 'Chance: Has a chance to cause bleeding on a target that damages you.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16253', 'Chance: Has a chance to regenerate CP when you take damage.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16254', 'Chance: Has a chance to increase critical attack rate when you take damage.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16255', 'Chance: Has a chance to decrease the will to attack of a target that damages you.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16256', 'Chance: Has a chance to increase your Accuracy when you take damage.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16257', 'Chance: Has a chance to hold a target that damages you. Your target cannot be affected by any additional hold attacks while the effect lasts.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16258', 'Chance: Has a chance to increase the effectiveness of HP recovery magic when you take damage.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16259', 'Chance: Has a chance to regenerate HP when you take damage.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16260', 'Chance: Has a chance to increase your M. Atk. when you take damage.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16261', 'Chance: Has a chance to increase critical attack rate of magic attacks when you take damage.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16262', 'Chance: Has a chance to increase your maximum CP when you take damage.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16263', 'Chance: Has a chance to increase your maximum HP when you take damage.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16264', 'Chance: Has a chance to increase your maximum MP when you take damage.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16265', 'Chance: Has a chance to increase your M. Def. when you take damage.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16266', 'Chance: Has a chance to increase your P. Atk. when you take damage.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16267', 'Chance: Has a chance to increase your P. Def. when you take damage.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16268', 'Chance: Has a chance to poison a target that damages you.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16269', 'Chance: Has a chance to decrease the PVP power of a target that damages you in PvP.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16270', 'Chance: Has a chance to increase your PVP power when you take damage in PvP.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16271', 'Chance: Has a chance to sleep a target that damages you. Your target cannot be affected by any additional sleep attacks while the effect lasts.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16272', 'Chance: Has a chance to decrease the speed of a target that damages you in PvP.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16273', 'Chance: Momentarily decreases your target\'s Atk. Spd. during a magic attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16274', 'Chance: Momentarily causes your target to bleed during a magic attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16275', 'Chance: Momentarily frightens away your target during a magic attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16276', 'Chance: Momentarily holds your target during a magic attack. Your target cannot be affected by any additional hold attacks while the effect lasts.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16277', 'Chance: Momentarily poisons your target during a magic attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16278', 'Chance: Momentarily petrifies your target during a magic attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16279', 'Passive: Increases the power of HP recovery magic.', '3');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16280', 'Passive: Increases the effectiveness of HP recovery magic.', '3');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16281', 'Passive: Increases your M. Atk.', '3');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16282', 'Passive: Increases your M. Def.', '3');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16283', 'Passive: Increases your P. Atk.', '3');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16284', 'Passive: Increases your P. Def.', '3');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16285', 'Passive: Increases your P. Atk. in PvP.', '3');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16286', 'Passive: Increases your weight limit by 2.', '3');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16287', 'Active: Temporarily decreases all skill re-use times.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16288', 'Active: Temporarily decreases MP consumption rates for all skills.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16289', 'Active: Temporarily increases your critical attack rate.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16290', 'Active: Temporarily reflects some of the damage you receive back to the enemy. Excludes damage from skills or ranged attacks.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16291', 'Active: Temporarily blocks all of your target\'s physical/magic skills.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16292', 'Active: Teleports you to the nearest village. Cannot be used in a specially designated place such as the GM Consultation Service.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16293', 'Active: Renders you momentarily invincible.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16294', 'Active: Temporarily increases your critical attack rate for magic attacks.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16295', 'Active: Teleports party members to a village. Cannot be used in a specially designated place such as the GM Consultation Service.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16296', 'Active: Temporarily blocks your target\'s magic skills.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16297', 'Active: Temporarily decreases the skill re-use time.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16298', 'Active: Temporarily decreases the skill MP consumption rate.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16299', 'Active: Temporarily decreases the re-use time for singing and dancing skills.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16300', 'Active: Temporarily decreases the MP consumption rate for singing and dancing skills.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16301', 'Active: Temporarily decreases the magic re-use time.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16302', 'Active: Temporarily decreases the magic MP consumption rate.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16303', 'Active: Temporarily blocks a monster\'s pre-emptive attack. Fighting ability significantly decreases while in effect.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16304', 'Active: Temporarily increases the amount of HP absorbed from damage done to your target. Excludes damage by skill or ranged attacks.', '1');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16305', 'Chance: Momentarily blocks all of your target\'s physical and magic skills during a physical attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16306', 'Chance: Momentarily burns up your target\'s MP during a physical attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16307', 'Chance: Momentarily paralyzes your target during a physical attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16308', 'Chance: Momentarily blocks your target\'s magic skill during a physical attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16309', 'Chance: Momentarily puts your target to sleep during a physical attack. Your target cannot be affected by any additional sleep attacks while the effect lasts.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16310', 'Chance: Momentarily stuns your target during a physical attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16311', 'Chance: Momentarily blocks all of your target\'s physical and magic skills during a critical attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16312', 'Chance: Momentarily burns up your target\'s MP during a critical attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16313', 'Chance: Momentarily paralyzes your target during a critical attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16314', 'Chance: Momentarily blocks your target\'s magic skill during a critical attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16315', 'Chance: Momentarily puts your target to sleep during a critical attack. Your target cannot be affected by any additional sleep attacks while the effect lasts.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16316', 'Chance: Momentarily stuns your target during a critical attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16317', 'Chance: Has a chance to block the use of all physical and magical skills by a target that damages you.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16318', 'Chance: Has a chance to frighten away a target that damages you.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16319', 'Chance: Has a chance to increase the effectiveness of MP recovery magic when you take damage.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16320', 'Chance: Has a chance to regenerate MP when you take damage.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16321', 'Chance: Has a chance to paralyze a target that damages you.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16322', 'Chance: Has a chance to block the use of all magic skills by a target that damages you.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16323', 'Chance: Has a chance to stun a target that damages you.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16324', 'Chance: Has a chance to petrify a target that damages you.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16325', 'Chance: Momentarily blocks all of your target\'s physical and magic skills during a magic attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16326', 'Chance: Momentarily burns up your target\'s MP during a magic attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16327', 'Chance: Momentarily paralyzes your target during a magic attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16328', 'Chance: Momentarily blocks your target\'s magic skill during a magic attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16329', 'Chance: Momentarily puts your target to sleep during a magic attack. Your target cannot be affected by any additional sleep attacks while the effect lasts.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16330', 'Chance: Momentarily stuns your target during a magic attack.', '2');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16331', 'Passive: Decreases the MP consumption rate for all skills.', '3');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16332', 'Passive: Increases your Evasion.', '3');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16333', 'Passive: Increases your critical attack rate.', '3');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16334', 'Passive: Increases the ability to reflect some of the damage you incurred back to the enemy. Excludes damage by skill or ranged attacks.', '3');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16335', 'Passive: Increases your Accuracy.', '3');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16336', 'Passive: Increases the critical attack rate of magic attacks.', '3');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16337', 'Passive: Increases your MP recharge recovery rate.', '3');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16338', 'Passive: Decreases the skill MP consumption rate.', '3');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16339', 'Passive: Decreases the song/dance skill MP consumption rate.', '3');
INSERT INTO `augment_attribute` (`id`, `description`, `type`) VALUES ('16340', 'Passive: Decreases the magic MP consumption rate.', '3');
